"""
CodeWriter – Gerador de Assembly Hack

Responsável por traduzir comandos VM para instruções .asm válidas
para a CPU Hack (Nand2Tetris Projects 07 e 08).

Segmentos suportados: constant, local, argument, this, that,
                      temp, pointer, static.
Operações suportadas: add, sub, neg, eq, gt, lt, and, or, not.
"""

from __future__ import annotations

import os
from typing import IO

_SEGMENT_BASE: dict[str, str] = {
    "local":    "LCL",
    "argument": "ARG",
    "this":     "THIS",
    "that":     "THAT",
}

_TEMP_BASE = 5

_POINTER_BASE = 3


class CodeWriter:
    """Traduz comandos VM para assembly Hack e escreve no arquivo de saída."""

    def __init__(self, filename: str) -> None:
        """
        Abre o arquivo .asm de saída para escrita.

        Args:
            filename: Caminho do arquivo .asm a ser gerado.
        """
        self._file: IO[str] = open(filename, "w", encoding="utf-8")
        self._static_prefix: str = os.path.splitext(os.path.basename(filename))[0]
        self._label_counter: int = 0
        self._return_counter: int = 0
        self._current_function: str = ""
        self._write_comment(f"Generated by VMTranslator – {filename}")

    def write_init(self) -> None:
        """Inicializa SP e chama a função de entrada ``Sys.init``."""
        self._write_comment("bootstrap")
        self._emit("@256")
        self._emit("D=A")
        self._emit("@SP")
        self._emit("M=D")
        self.write_call("Sys.init", 0)

    def write_arithmetic(self, cmd: str) -> None:
        """
        Gera código Assembly para operações aritméticas e lógicas.

        Args:
            cmd: Um de: add, sub, neg, eq, gt, lt, and, or, not.

        Raises:
            ValueError: Se o comando não for reconhecido.
        """
        self._write_comment(f"arithmetic: {cmd}")

        if cmd == "add":
            self._write_binary_op("D+M")
        elif cmd == "sub":
            self._write_binary_op("M-D")
        elif cmd == "neg":
            self._write_unary_op("-M")
        elif cmd == "and":
            self._write_binary_op("D&M")
        elif cmd == "or":
            self._write_binary_op("D|M")
        elif cmd == "not":
            self._write_unary_op("!M")
        elif cmd in {"eq", "gt", "lt"}:
            self._write_comparison(cmd)
        else:
            raise ValueError(f"Unknown arithmetic command: {cmd!r}")

    def write_push(self, segment: str, index: int) -> None:
        """
        Gera código Assembly para empilhar um valor na pilha.

        Args:
            segment: Segmento de memória VM.
            index:   Índice dentro do segmento.
        """
        self._write_comment(f"push {segment} {index}")
        self._resolve_push(segment, index)
        self._push_d()

    def write_pop(self, segment: str, index: int) -> None:
        """
        Gera código Assembly para desempilhar um valor da pilha.

        Args:
            segment: Segmento de memória VM (não pode ser 'constant').
            index:   Índice dentro do segmento.

        Raises:
            ValueError: Se tentar fazer pop no segmento constant.
        """
        if segment == "constant":
            raise ValueError("Cannot pop to the 'constant' segment.")
        self._write_comment(f"pop {segment} {index}")
        self._resolve_pop(segment, index)

    def write_label(self, label: str) -> None:
        """Declara um label no escopo da função atual."""
        scoped_label = self._scoped_label(label)
        self._write_comment(f"label {label}")
        self._emit(f"({scoped_label})")

    def write_goto(self, label: str) -> None:
        """Gera um salto incondicional para um label da função atual."""
        scoped_label = self._scoped_label(label)
        self._write_comment(f"goto {label}")
        self._emit(f"@{scoped_label}")
        self._emit("0;JMP")

    def write_if(self, label: str) -> None:
        """Salta para o label quando o valor desempilhado for diferente de zero."""
        scoped_label = self._scoped_label(label)
        self._write_comment(f"if-goto {label}")
        self._decrement_sp_to_d()
        self._emit(f"@{scoped_label}")
        self._emit("D;JNE")

    def write_call(self, function_name: str, n_args: int) -> None:
        """Gera o frame do chamador e transfere o controle para uma função."""
        if n_args < 0:
            raise ValueError("The number of call arguments cannot be negative")

        return_label = f"VM$ret.{self._return_counter}"
        self._return_counter += 1
        self._write_comment(f"call {function_name} {n_args}")

        self._emit(f"@{return_label}")
        self._emit("D=A")
        self._push_d()

        for segment in ("LCL", "ARG", "THIS", "THAT"):
            self._emit(f"@{segment}")
            self._emit("D=M")
            self._push_d()

        self._emit("@SP")
        self._emit("D=M")
        self._emit("@5")
        self._emit("D=D-A")
        self._emit(f"@{n_args}")
        self._emit("D=D-A")
        self._emit("@ARG")
        self._emit("M=D")

        self._emit("@SP")
        self._emit("D=M")
        self._emit("@LCL")
        self._emit("M=D")

        self._emit(f"@{function_name}")
        self._emit("0;JMP")
        self._emit(f"({return_label})")

    def close(self) -> None:
        """Finaliza o arquivo com loop infinito e fecha."""
        self._write_comment("end of program – infinite loop")
        self._emit("(END)")
        self._emit("@END")
        self._emit("0;JMP")
        self._file.close()

    def NewCodeWriter(self, filename: str) -> "CodeWriter":  
        return CodeWriter(filename)

    def WriteArithmetic(self, cmd: str) -> None:  
        self.write_arithmetic(cmd)

    def WriteInit(self) -> None:  # noqa: N802
        self.write_init()

    def WritePush(self, segment: str, index: int) -> None:  
        self.write_push(segment, index)

    def WritePop(self, segment: str, index: int) -> None:  
        self.write_pop(segment, index)

    def WriteLabel(self, label: str) -> None:  # noqa: N802
        self.write_label(label)

    def WriteGoto(self, label: str) -> None:  # noqa: N802
        self.write_goto(label)

    def WriteIf(self, label: str) -> None:  # noqa: N802
        self.write_if(label)

    def WriteCall(self, function_name: str, n_args: int) -> None:  # noqa: N802
        self.write_call(function_name, n_args)

    def Close(self) -> None:  
        self.close()

    def _write_binary_op(self, comp: str) -> None:
        """Operações binárias: desempilha D e M, aplica comp, empilha."""
        self._emit("@SP")
        self._emit("AM=M-1")  
        self._emit("D=M")      
        self._emit("A=A-1")    
        self._emit(f"M={comp}")  

    def _write_unary_op(self, comp: str) -> None:
        """Operações unárias: opera diretamente no topo da pilha."""
        self._emit("@SP")
        self._emit("A=M-1")    
        self._emit(f"M={comp}")

    def _write_comparison(self, cmd: str) -> None:
        """
        Gera código para comparações (eq, gt, lt).

        Usa labels únicos para evitar colisão em múltiplos usos.
        Resultado: -1 (true) ou 0 (false) no topo da pilha.
        """
        jump_map = {"eq": "JEQ", "gt": "JGT", "lt": "JLT"}
        jump = jump_map[cmd]
        label_true = f"CMP_TRUE_{self._label_counter}"
        label_end  = f"CMP_END_{self._label_counter}"
        self._label_counter += 1
        self._emit("@SP")
        self._emit("AM=M-1")
        self._emit("D=M")      
        self._emit("A=A-1")    
        self._emit("D=M-D")    
        self._emit(f"@{label_true}")
        self._emit(f"D;{jump}")
        self._emit("@SP")
        self._emit("A=M-1")
        self._emit("M=0")
        self._emit(f"@{label_end}")
        self._emit("0;JMP")
        self._emit(f"({label_true})")
        self._emit("@SP")
        self._emit("A=M-1")
        self._emit("M=-1")

        self._emit(f"({label_end})")

    def _resolve_push(self, segment: str, index: int) -> None:
        """Carrega o valor do segmento em D, pronto para _push_d()."""

        if segment == "constant":
            self._emit(f"@{index}")
            self._emit("D=A")

        elif segment in _SEGMENT_BASE:
            base_reg = _SEGMENT_BASE[segment]
            self._emit(f"@{index}")
            self._emit("D=A")
            self._emit(f"@{base_reg}")
            self._emit("A=D+M") 
            self._emit("D=M")

        elif segment == "temp":
            addr = _TEMP_BASE + index
            self._emit(f"@{addr}")
            self._emit("D=M")

        elif segment == "pointer":
            addr = _POINTER_BASE + index  
            self._emit(f"@{addr}")
            self._emit("D=M")

        elif segment == "static":
            symbol = f"{self._static_prefix}.{index}"
            self._emit(f"@{symbol}")
            self._emit("D=M")

        else:
            raise ValueError(f"Unknown segment: {segment!r}")

    def _push_d(self) -> None:
        """Empilha o valor em D e incrementa SP."""
        self._emit("@SP")
        self._emit("A=M")
        self._emit("M=D")   
        self._emit("@SP")
        self._emit("M=M+1") 

    def _resolve_pop(self, segment: str, index: int) -> None:
        """
        Desempilha o topo da pilha e armazena no endereço alvo.

        Estratégia geral:
          1. Calcula endereço alvo → armazena em R13 (registrador temporário).
          2. Desempilha SP em D.
          3. Usa R13 como ponteiro para escrever D.
        """
        if segment in _SEGMENT_BASE:
            base_reg = _SEGMENT_BASE[segment]
            self._emit(f"@{index}")
            self._emit("D=A")
            self._emit(f"@{base_reg}")
            self._emit("D=D+M")
            self._emit("@R13")
            self._emit("M=D")
            self._decrement_sp_to_d()
            self._emit("@R13")
            self._emit("A=M")
            self._emit("M=D")

        elif segment == "temp":
            addr = _TEMP_BASE + index
            self._decrement_sp_to_d()
            self._emit(f"@{addr}")
            self._emit("M=D")

        elif segment == "pointer":
            addr = _POINTER_BASE + index
            self._decrement_sp_to_d()
            self._emit(f"@{addr}")
            self._emit("M=D")

        elif segment == "static":
            symbol = f"{self._static_prefix}.{index}"
            self._decrement_sp_to_d()
            self._emit(f"@{symbol}")
            self._emit("M=D")

        else:
            raise ValueError(f"Unknown segment: {segment!r}")

    def _decrement_sp_to_d(self) -> None:
        """Decrementa SP e carrega o valor do topo em D."""
        self._emit("@SP")
        self._emit("AM=M-1")
        self._emit("D=M")

    def _scoped_label(self, label: str) -> str:
        """Qualifica labels locais quando há uma função em tradução."""
        if self._current_function:
            return f"{self._current_function}${label}"
        return label

    def _emit(self, line: str) -> None:
        """Escreve uma linha de assembly no arquivo de saída."""
        self._file.write(line + "\n")

    def _write_comment(self, text: str) -> None:
        """Escreve um comentário legível no arquivo de saída."""
        self._file.write(f"// {text}\n")

    def write_function(self, name: str, n_locals: int) -> None:
        """Declara uma função e reserva espaço para suas variáveis locais."""
        self._current_function = name
        self._write_comment(f"function {name} {n_locals}")
        self._emit(f"({name})")
        for _ in range(n_locals):
            self.write_push("constant", 0)

    def WriteFunction(self, name: str, n_locals: int) -> None: 
        self.write_function(name, n_locals)

    def write_return(self) -> None:
        """Gera o código para retornar de uma função."""
        self._write_comment("return")
        self._emit("@LCL")
        self._emit("D=M")
        self._emit("@R13") 
        self._emit("M=D")
        self._emit("@5")
        self._emit("A=D-A")
        self._emit("D=M")
        self._emit("@R14") 
        self._emit("M=D")
        self._decrement_sp_to_d()
        self._emit("@ARG")
        self._emit("A=M")
        self._emit("M=D") 
        self._emit("@ARG")
        self._emit("D=M+1")
        self._emit("@SP")
        self._emit("M=D")
        for i, segment in enumerate(["THAT", "THIS", "ARG", "LCL"], 1):
            self._emit("@R13")
            self._emit("D=M")
            self._emit(f"@{i}")
            self._emit("A=D-A")
            self._emit("D=M")
            self._emit(f"@{segment}")
            self._emit("M=D")
        self._emit("@R14")
        self._emit("0;JMP") 

    def WriteReturn(self) -> None: 
        self.write_return()
